# TODO: enable after v0.1 code drop
on: [push, pull_request]
jobs:
  lint:
    if: "!contains(github.event.head_commit.message, '[skip-ci]') && false"
    runs-on: ubuntu-latest
    steps:
      - run: echo "work in progress"
